// <auto-generated />
using System;
using Mealplan.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mealplan.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ScrapeDbContext))]
    partial class ScrapeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("scrape")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mealplan.Domain.Scraping.ScrapeDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("ContentHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("content_hash");

                    b.Property<int>("DocumentType")
                        .HasColumnType("integer")
                        .HasColumnName("document_type");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("NormalizeError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("normalize_error");

                    b.Property<DateTimeOffset?>("NormalizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("normalized_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("source_key");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_document");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_document_run_id");

                    b.HasIndex("Source", "FirstSeenAt")
                        .HasDatabaseName("ix_document_pending_normalization")
                        .HasFilter("normalized_at IS NULL");

                    b.HasIndex("Source", "DocumentType", "SourceKey", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_document_source_document_type_source_key_version");

                    b.ToTable("document", "scrape");
                });

            modelBuilder.Entity("Mealplan.Domain.Scraping.ScrapeRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cursor")
                        .HasColumnType("jsonb")
                        .HasColumnName("cursor");

                    b.Property<int>("DocumentsChanged")
                        .HasColumnType("integer")
                        .HasColumnName("documents_changed");

                    b.Property<int>("DocumentsFetched")
                        .HasColumnType("integer")
                        .HasColumnName("documents_fetched");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_run");

                    b.HasIndex("Source", "StartedAt")
                        .HasDatabaseName("ix_run_source_started_at");

                    b.ToTable("run", "scrape");
                });
#pragma warning restore 612, 618
        }
    }
}
