// <auto-generated />
using System;
using Mealplan.Infrastructure.Gousto.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mealplan.Infrastructure.Gousto.Persistence.Migrations
{
    [DbContext(typeof(GoustoDbContext))]
    [Migration("20260719111914_InitialGoustoSchema")]
    partial class InitialGoustoSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("gousto")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mealplan.Infrastructure.Gousto.Persistence.GoustoAllergenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("slug");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_allergen");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_allergen_slug");

                    b.ToTable("allergen", "gousto");
                });

            modelBuilder.Entity("Mealplan.Infrastructure.Gousto.Persistence.GoustoCategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("uid");

                    b.Property<string>("Url")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_category");

                    b.HasIndex("Uid")
                        .IsUnique()
                        .HasDatabaseName("ix_category_uid");

                    b.ToTable("category", "gousto");
                });

            modelBuilder.Entity("Mealplan.Infrastructure.Gousto.Persistence.GoustoCuisineEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("slug");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_cuisine");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_cuisine_slug");

                    b.ToTable("cuisine", "gousto");
                });

            modelBuilder.Entity("Mealplan.Infrastructure.Gousto.Persistence.GoustoIngredientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("GoustoUuid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("gousto_uuid");

                    b.Property<string>("Label")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("label");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_ingredient");

                    b.HasIndex("GoustoUuid")
                        .IsUnique()
                        .HasDatabaseName("ix_ingredient_gousto_uuid");

                    b.ToTable("ingredient", "gousto");
                });

            modelBuilder.Entity("Mealplan.Infrastructure.Gousto.Persistence.GoustoNutritionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Basis")
                        .HasColumnType("integer")
                        .HasColumnName("basis");

                    b.Property<double?>("CarbsGrams")
                        .HasColumnType("double precision")
                        .HasColumnName("carbs_grams");

                    b.Property<double?>("EnergyKcal")
                        .HasColumnType("double precision")
                        .HasColumnName("energy_kcal");

                    b.Property<double?>("EnergyKj")
                        .HasColumnType("double precision")
                        .HasColumnName("energy_kj");

                    b.Property<double?>("FatGrams")
                        .HasColumnType("double precision")
                        .HasColumnName("fat_grams");

                    b.Property<double?>("FibreGrams")
                        .HasColumnType("double precision")
                        .HasColumnName("fibre_grams");

                    b.Property<double?>("NetWeightGrams")
                        .HasColumnType("double precision")
                        .HasColumnName("net_weight_grams");

                    b.Property<double?>("ProteinGrams")
                        .HasColumnType("double precision")
                        .HasColumnName("protein_grams");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<double?>("SaltGrams")
                        .HasColumnType("double precision")
                        .HasColumnName("salt_grams");

                    b.Property<double?>("SaturatedFatGrams")
                        .HasColumnType("double precision")
                        .HasColumnName("saturated_fat_grams");

                    b.Property<double?>("SugarsGrams")
                        .HasColumnType("double precision")
                        .HasColumnName("sugars_grams");

                    b.HasKey("Id")
                        .HasName("pk_recipe_nutrition");

                    b.HasIndex("RecipeId", "Basis")
                        .IsUnique()
                        .HasDatabaseName("ix_recipe_nutrition_recipe_id_basis");

                    b.ToTable("recipe_nutrition", "gousto");
                });

            modelBuilder.Entity("Mealplan.Infrastructure.Gousto.Persistence.GoustoPantryItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("slug");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_pantry_item");

                    b.HasIndex("RecipeId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_pantry_item_recipe_id_slug");

                    b.ToTable("pantry_item", "gousto");
                });

            modelBuilder.Entity("Mealplan.Infrastructure.Gousto.Persistence.GoustoRecipeAllergenEntity", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<Guid>("AllergenId")
                        .HasColumnType("uuid")
                        .HasColumnName("allergen_id");

                    b.HasKey("RecipeId", "AllergenId")
                        .HasName("pk_recipe_allergen");

                    b.HasIndex("AllergenId")
                        .HasDatabaseName("ix_recipe_allergen_allergen_id");

                    b.ToTable("recipe_allergen", "gousto");
                });

            modelBuilder.Entity("Mealplan.Infrastructure.Gousto.Persistence.GoustoRecipeCategoryEntity", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.HasKey("RecipeId", "CategoryId")
                        .HasName("pk_recipe_category");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_recipe_category_category_id");

                    b.ToTable("recipe_category", "gousto");
                });

            modelBuilder.Entity("Mealplan.Infrastructure.Gousto.Persistence.GoustoRecipeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CuisineId")
                        .HasColumnType("uuid")
                        .HasColumnName("cuisine_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("GoustoId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("gousto_id");

                    b.Property<string>("GoustoUid")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("gousto_uid");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<double?>("RatingAverage")
                        .HasColumnType("double precision")
                        .HasColumnName("rating_average");

                    b.Property<int?>("RatingCount")
                        .HasColumnType("integer")
                        .HasColumnName("rating_count");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("slug");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_recipe");

                    b.HasIndex("CuisineId")
                        .HasDatabaseName("ix_recipe_cuisine_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_recipe_slug");

                    b.ToTable("recipe", "gousto");
                });

            modelBuilder.Entity("Mealplan.Infrastructure.Gousto.Persistence.GoustoStepEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("InstructionHtml")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instruction_html");

                    b.Property<string>("InstructionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instruction_text");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.HasKey("Id")
                        .HasName("pk_recipe_step");

                    b.HasIndex("RecipeId", "Order")
                        .IsUnique()
                        .HasDatabaseName("ix_recipe_step_recipe_id_order");

                    b.ToTable("recipe_step", "gousto");
                });

            modelBuilder.Entity("Mealplan.Infrastructure.Gousto.Persistence.GoustoYieldEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsOffered")
                        .HasColumnType("boolean")
                        .HasColumnName("is_offered");

                    b.Property<int>("Portions")
                        .HasColumnType("integer")
                        .HasColumnName("portions");

                    b.Property<int?>("PrepMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("prep_minutes");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.HasKey("Id")
                        .HasName("pk_recipe_yield");

                    b.HasIndex("RecipeId", "Portions")
                        .IsUnique()
                        .HasDatabaseName("ix_recipe_yield_recipe_id_portions");

                    b.ToTable("recipe_yield", "gousto");
                });

            modelBuilder.Entity("Mealplan.Infrastructure.Gousto.Persistence.GoustoYieldIngredientEntity", b =>
                {
                    b.Property<Guid>("YieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("yield_id");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingredient_id");

                    b.Property<int?>("InBox")
                        .HasColumnType("integer")
                        .HasColumnName("in_box");

                    b.Property<string>("SkuCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("sku_code");

                    b.HasKey("YieldId", "IngredientId")
                        .HasName("pk_recipe_yield_ingredient");

                    b.HasIndex("IngredientId")
                        .HasDatabaseName("ix_recipe_yield_ingredient_ingredient_id");

                    b.ToTable("recipe_yield_ingredient", "gousto");
                });

            modelBuilder.Entity("Mealplan.Infrastructure.Gousto.Persistence.GoustoNutritionEntity", b =>
                {
                    b.HasOne("Mealplan.Infrastructure.Gousto.Persistence.GoustoRecipeEntity", "Recipe")
                        .WithMany("Nutrition")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_nutrition_recipe_recipe_id");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Mealplan.Infrastructure.Gousto.Persistence.GoustoPantryItemEntity", b =>
                {
                    b.HasOne("Mealplan.Infrastructure.Gousto.Persistence.GoustoRecipeEntity", "Recipe")
                        .WithMany("PantryItems")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pantry_item_recipe_recipe_id");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Mealplan.Infrastructure.Gousto.Persistence.GoustoRecipeAllergenEntity", b =>
                {
                    b.HasOne("Mealplan.Infrastructure.Gousto.Persistence.GoustoAllergenEntity", "Allergen")
                        .WithMany()
                        .HasForeignKey("AllergenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_allergen_allergen_allergen_id");

                    b.HasOne("Mealplan.Infrastructure.Gousto.Persistence.GoustoRecipeEntity", "Recipe")
                        .WithMany("Allergens")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_allergen_recipe_recipe_id");

                    b.Navigation("Allergen");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Mealplan.Infrastructure.Gousto.Persistence.GoustoRecipeCategoryEntity", b =>
                {
                    b.HasOne("Mealplan.Infrastructure.Gousto.Persistence.GoustoCategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_category_category_category_id");

                    b.HasOne("Mealplan.Infrastructure.Gousto.Persistence.GoustoRecipeEntity", "Recipe")
                        .WithMany("Categories")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_category_recipe_recipe_id");

                    b.Navigation("Category");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Mealplan.Infrastructure.Gousto.Persistence.GoustoRecipeEntity", b =>
                {
                    b.HasOne("Mealplan.Infrastructure.Gousto.Persistence.GoustoCuisineEntity", "Cuisine")
                        .WithMany()
                        .HasForeignKey("CuisineId")
                        .HasConstraintName("fk_recipe_cuisines_cuisine_id");

                    b.Navigation("Cuisine");
                });

            modelBuilder.Entity("Mealplan.Infrastructure.Gousto.Persistence.GoustoStepEntity", b =>
                {
                    b.HasOne("Mealplan.Infrastructure.Gousto.Persistence.GoustoRecipeEntity", "Recipe")
                        .WithMany("Steps")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_step_recipe_recipe_id");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Mealplan.Infrastructure.Gousto.Persistence.GoustoYieldEntity", b =>
                {
                    b.HasOne("Mealplan.Infrastructure.Gousto.Persistence.GoustoRecipeEntity", "Recipe")
                        .WithMany("Yields")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_yield_recipe_recipe_id");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Mealplan.Infrastructure.Gousto.Persistence.GoustoYieldIngredientEntity", b =>
                {
                    b.HasOne("Mealplan.Infrastructure.Gousto.Persistence.GoustoIngredientEntity", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_yield_ingredient_ingredient_ingredient_id");

                    b.HasOne("Mealplan.Infrastructure.Gousto.Persistence.GoustoYieldEntity", "Yield")
                        .WithMany("Ingredients")
                        .HasForeignKey("YieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_yield_ingredient_recipe_yield_yield_id");

                    b.Navigation("Ingredient");

                    b.Navigation("Yield");
                });

            modelBuilder.Entity("Mealplan.Infrastructure.Gousto.Persistence.GoustoRecipeEntity", b =>
                {
                    b.Navigation("Allergens");

                    b.Navigation("Categories");

                    b.Navigation("Nutrition");

                    b.Navigation("PantryItems");

                    b.Navigation("Steps");

                    b.Navigation("Yields");
                });

            modelBuilder.Entity("Mealplan.Infrastructure.Gousto.Persistence.GoustoYieldEntity", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
