// <auto-generated />
using System;
using Mealplan.Infrastructure.HelloFresh.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mealplan.Infrastructure.HelloFresh.Persistence.Migrations
{
    [DbContext(typeof(HelloFreshDbContext))]
    [Migration("20260719124908_InitialHelloFreshSchema")]
    partial class InitialHelloFreshSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("hellofresh")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mealplan.Infrastructure.HelloFresh.Persistence.HelloFreshAllergenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_allergen");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_allergen_external_id");

                    b.ToTable("allergen", "hellofresh");
                });

            modelBuilder.Entity("Mealplan.Infrastructure.HelloFresh.Persistence.HelloFreshCategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_category");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_category_external_id");

                    b.ToTable("category", "hellofresh");
                });

            modelBuilder.Entity("Mealplan.Infrastructure.HelloFresh.Persistence.HelloFreshCuisineEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_cuisine");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_cuisine_external_id");

                    b.ToTable("cuisine", "hellofresh");
                });

            modelBuilder.Entity("Mealplan.Infrastructure.HelloFresh.Persistence.HelloFreshIngredientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_id");

                    b.Property<string>("Family")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("family");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_ingredient");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_ingredient_external_id");

                    b.ToTable("ingredient", "hellofresh");
                });

            modelBuilder.Entity("Mealplan.Infrastructure.HelloFresh.Persistence.HelloFreshNutritionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("Amount")
                        .HasColumnType("double precision")
                        .HasColumnName("amount");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<string>("Unit")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("pk_recipe_nutrition");

                    b.HasIndex("RecipeId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_recipe_nutrition_recipe_id_name");

                    b.ToTable("recipe_nutrition", "hellofresh");
                });

            modelBuilder.Entity("Mealplan.Infrastructure.HelloFresh.Persistence.HelloFreshRecipeAllergenEntity", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<Guid>("AllergenId")
                        .HasColumnType("uuid")
                        .HasColumnName("allergen_id");

                    b.Property<bool>("TracesOf")
                        .HasColumnType("boolean")
                        .HasColumnName("traces_of");

                    b.HasKey("RecipeId", "AllergenId")
                        .HasName("pk_recipe_allergen");

                    b.HasIndex("AllergenId")
                        .HasDatabaseName("ix_recipe_allergen_allergen_id");

                    b.ToTable("recipe_allergen", "hellofresh");
                });

            modelBuilder.Entity("Mealplan.Infrastructure.HelloFresh.Persistence.HelloFreshRecipeCuisineEntity", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<Guid>("CuisineId")
                        .HasColumnType("uuid")
                        .HasColumnName("cuisine_id");

                    b.HasKey("RecipeId", "CuisineId")
                        .HasName("pk_recipe_cuisine");

                    b.HasIndex("CuisineId")
                        .HasDatabaseName("ix_recipe_cuisine_cuisine_id");

                    b.ToTable("recipe_cuisine", "hellofresh");
                });

            modelBuilder.Entity("Mealplan.Infrastructure.HelloFresh.Persistence.HelloFreshRecipeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("AverageRating")
                        .HasColumnType("double precision")
                        .HasColumnName("average_rating");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("Difficulty")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_id");

                    b.Property<string>("Headline")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("headline");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<int?>("PrepMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("prep_minutes");

                    b.Property<int?>("RatingsCount")
                        .HasColumnType("integer")
                        .HasColumnName("ratings_count");

                    b.Property<double?>("ServingSizeGrams")
                        .HasColumnType("double precision")
                        .HasColumnName("serving_size_grams");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("slug");

                    b.Property<int?>("TotalMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("total_minutes");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("website_url");

                    b.HasKey("Id")
                        .HasName("pk_recipe");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_recipe_category_id");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_recipe_external_id");

                    b.HasIndex("Slug")
                        .HasDatabaseName("ix_recipe_slug");

                    b.ToTable("recipe", "hellofresh");
                });

            modelBuilder.Entity("Mealplan.Infrastructure.HelloFresh.Persistence.HelloFreshRecipeTagEntity", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.HasKey("RecipeId", "TagId")
                        .HasName("pk_recipe_tag");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_recipe_tag_tag_id");

                    b.ToTable("recipe_tag", "hellofresh");
                });

            modelBuilder.Entity("Mealplan.Infrastructure.HelloFresh.Persistence.HelloFreshRecipeUtensilEntity", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<Guid>("UtensilId")
                        .HasColumnType("uuid")
                        .HasColumnName("utensil_id");

                    b.HasKey("RecipeId", "UtensilId")
                        .HasName("pk_recipe_utensil");

                    b.HasIndex("UtensilId")
                        .HasDatabaseName("ix_recipe_utensil_utensil_id");

                    b.ToTable("recipe_utensil", "hellofresh");
                });

            modelBuilder.Entity("Mealplan.Infrastructure.HelloFresh.Persistence.HelloFreshStepEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instructions");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.HasKey("Id")
                        .HasName("pk_recipe_step");

                    b.HasIndex("RecipeId", "Index")
                        .IsUnique()
                        .HasDatabaseName("ix_recipe_step_recipe_id_index");

                    b.ToTable("recipe_step", "hellofresh");
                });

            modelBuilder.Entity("Mealplan.Infrastructure.HelloFresh.Persistence.HelloFreshTagEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_tag");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_tag_external_id");

                    b.ToTable("tag", "hellofresh");
                });

            modelBuilder.Entity("Mealplan.Infrastructure.HelloFresh.Persistence.HelloFreshUtensilEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_utensil");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_utensil_external_id");

                    b.ToTable("utensil", "hellofresh");
                });

            modelBuilder.Entity("Mealplan.Infrastructure.HelloFresh.Persistence.HelloFreshYieldEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Portions")
                        .HasColumnType("integer")
                        .HasColumnName("portions");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.HasKey("Id")
                        .HasName("pk_recipe_yield");

                    b.HasIndex("RecipeId", "Portions")
                        .IsUnique()
                        .HasDatabaseName("ix_recipe_yield_recipe_id_portions");

                    b.ToTable("recipe_yield", "hellofresh");
                });

            modelBuilder.Entity("Mealplan.Infrastructure.HelloFresh.Persistence.HelloFreshYieldIngredientEntity", b =>
                {
                    b.Property<Guid>("YieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("yield_id");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingredient_id");

                    b.Property<double?>("Amount")
                        .HasColumnType("double precision")
                        .HasColumnName("amount");

                    b.Property<string>("Unit")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("unit");

                    b.HasKey("YieldId", "IngredientId")
                        .HasName("pk_recipe_yield_ingredient");

                    b.HasIndex("IngredientId")
                        .HasDatabaseName("ix_recipe_yield_ingredient_ingredient_id");

                    b.ToTable("recipe_yield_ingredient", "hellofresh");
                });

            modelBuilder.Entity("Mealplan.Infrastructure.HelloFresh.Persistence.HelloFreshNutritionEntity", b =>
                {
                    b.HasOne("Mealplan.Infrastructure.HelloFresh.Persistence.HelloFreshRecipeEntity", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_nutrition_recipe_recipe_id");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Mealplan.Infrastructure.HelloFresh.Persistence.HelloFreshRecipeAllergenEntity", b =>
                {
                    b.HasOne("Mealplan.Infrastructure.HelloFresh.Persistence.HelloFreshAllergenEntity", "Allergen")
                        .WithMany()
                        .HasForeignKey("AllergenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_allergen_allergen_allergen_id");

                    b.HasOne("Mealplan.Infrastructure.HelloFresh.Persistence.HelloFreshRecipeEntity", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_allergen_recipe_recipe_id");

                    b.Navigation("Allergen");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Mealplan.Infrastructure.HelloFresh.Persistence.HelloFreshRecipeCuisineEntity", b =>
                {
                    b.HasOne("Mealplan.Infrastructure.HelloFresh.Persistence.HelloFreshCuisineEntity", "Cuisine")
                        .WithMany()
                        .HasForeignKey("CuisineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_cuisine_cuisine_cuisine_id");

                    b.HasOne("Mealplan.Infrastructure.HelloFresh.Persistence.HelloFreshRecipeEntity", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_cuisine_recipe_recipe_id");

                    b.Navigation("Cuisine");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Mealplan.Infrastructure.HelloFresh.Persistence.HelloFreshRecipeEntity", b =>
                {
                    b.HasOne("Mealplan.Infrastructure.HelloFresh.Persistence.HelloFreshCategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("fk_recipe_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Mealplan.Infrastructure.HelloFresh.Persistence.HelloFreshRecipeTagEntity", b =>
                {
                    b.HasOne("Mealplan.Infrastructure.HelloFresh.Persistence.HelloFreshRecipeEntity", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_tag_recipe_recipe_id");

                    b.HasOne("Mealplan.Infrastructure.HelloFresh.Persistence.HelloFreshTagEntity", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_tag_tag_tag_id");

                    b.Navigation("Recipe");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Mealplan.Infrastructure.HelloFresh.Persistence.HelloFreshRecipeUtensilEntity", b =>
                {
                    b.HasOne("Mealplan.Infrastructure.HelloFresh.Persistence.HelloFreshRecipeEntity", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_utensil_recipe_recipe_id");

                    b.HasOne("Mealplan.Infrastructure.HelloFresh.Persistence.HelloFreshUtensilEntity", "Utensil")
                        .WithMany()
                        .HasForeignKey("UtensilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_utensil_utensil_utensil_id");

                    b.Navigation("Recipe");

                    b.Navigation("Utensil");
                });

            modelBuilder.Entity("Mealplan.Infrastructure.HelloFresh.Persistence.HelloFreshStepEntity", b =>
                {
                    b.HasOne("Mealplan.Infrastructure.HelloFresh.Persistence.HelloFreshRecipeEntity", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_step_recipe_recipe_id");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Mealplan.Infrastructure.HelloFresh.Persistence.HelloFreshYieldEntity", b =>
                {
                    b.HasOne("Mealplan.Infrastructure.HelloFresh.Persistence.HelloFreshRecipeEntity", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_yield_recipe_recipe_id");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Mealplan.Infrastructure.HelloFresh.Persistence.HelloFreshYieldIngredientEntity", b =>
                {
                    b.HasOne("Mealplan.Infrastructure.HelloFresh.Persistence.HelloFreshIngredientEntity", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_yield_ingredient_ingredient_ingredient_id");

                    b.HasOne("Mealplan.Infrastructure.HelloFresh.Persistence.HelloFreshYieldEntity", "Yield")
                        .WithMany()
                        .HasForeignKey("YieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_yield_ingredient_recipe_yield_yield_id");

                    b.Navigation("Ingredient");

                    b.Navigation("Yield");
                });
#pragma warning restore 612, 618
        }
    }
}
